# =============================================================================
# ARGOCD APPLICATION: app-1
# This tells ArgoCD to watch the k8s/app-1/ directory in our Git repo
# and automatically sync those manifests to the EKS cluster.
#
# Image Updater Annotations:
#   - Watches the ECR repo for new semver tags (v0.1.0, v0.1.1, etc.)
#   - Automatically updates the image tag in the deployment
# =============================================================================
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-1
  namespace: argocd
  annotations:
    # --- Image Updater: Watch ECR for new tags ---
    argocd-image-updater.argoproj.io/image-list: app=585008053249.dkr.ecr.eu-west-1.amazonaws.com/muhirwajd/app-1
    argocd-image-updater.argoproj.io/app.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: git
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/muhirwaJD/Kubernetes-Cloud.git
    targetRevision: main
    path: aws/gitops/k8s/app-1  # Directory containing the K8s manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: app-1
  syncPolicy:
    automated:
      selfHeal: true   # Fix drift if someone manually changes a resource
      prune: true      # Delete resources removed from Git
    syncOptions:
      - CreateNamespace=true
